version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mikefox-3d-print-cost_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/mikefox303/3d-print-cost-umbrel:0.9.0-dev.1@sha256:32ad05edf930103b69c458af43528bd3f44c4ed3f01c9a97aaacad2f4ad9bd62
    restart: on-failure
    stop_grace_period: 30s
    init: true
    user: "1000:1000"
    environment:
      DATA_DIR: /data
      PORT: 8080
    volumes:
      - ${APP_DATA_DIR}/data:/data
