version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mikefox-3d-print-cost_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/mikefox303/3d-print-cost-umbrel:0.13.0-dev.1@sha256:8a085a84505362b00802a5f611eee6f0ee69a4b5aa7f040803a1b398aa071bc3
    restart: on-failure
    stop_grace_period: 30s
    init: true
    user: "1000:1000"
    environment:
      DATA_DIR: /data
      PORT: 8080
    volumes:
      - ${APP_DATA_DIR}/data:/data
