version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mikefox-3d-print-cost_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/mikefox303/3d-print-cost-umbrel:0.12.0-dev.1@sha256:2066ba5d26be9821a2778637b4a26636ec759edd21c53d69217616014883b550
    restart: on-failure
    stop_grace_period: 30s
    init: true
    user: "1000:1000"
    environment:
      DATA_DIR: /data
      PORT: 8080
    volumes:
      - ${APP_DATA_DIR}/data:/data
